apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-petcart-deployment
  namespace: admin-petcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-petcart
  template:
    metadata:
      labels:
        app: admin-petcart
    spec:
      containers:
        - name: admin-petcart
          image: 867809929056.dkr.ecr.us-east-1.amazonaws.com/admin-petcart:latest
          ports:
            - containerPort: 80
