apiVersion: v1
kind: Service
metadata:
  name: admin-petcart-service
  namespace: admin-petcart
spec:
  type: ClusterIP
  selector:
    app: admin-petcart
  ports:
    - port: 80
      targetPort: 80
